version: 'latest'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - project_network
  
  python_scripts:
    command: ["python", "etl_script.py"]
    context: ./files
    depends_on:
      - db
    networks:
      - project_network
  
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    ports:
      - "8080:80"
    networks:
      - project_network


networks:
  project_network:
    driver: bridge