version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - etl_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  elt_script:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - etl_network
    depends_on:
      db:
        condition: service_healthy
  
networks:
  etl_network:
    driver: bridge