version: 'latest'

services:
  db:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - project_network
    cap_add:
      - SYS_NICE
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./databases/init.sql:/docker-entrypoint-initdb.d/init.sql

  python_scripts:
    command: ["python", "etl_script.py"]
    container_name: python_script
    build:
      context: ./files
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - project_network
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    ports:
      - "8080:80"
    networks:
      - project_network


networks:
  project_network:
    driver: bridge