version: '2'

services:
  source_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - etl_network
    ports:
      - 5555:5554
  destination_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - etl_network
    ports:
      - 5556:5554
  elt_script:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    command: ["python", "elt_script.py"]
    networks:
      - etl_network
    restart: on-failure
    depends_on:
      - source_db
      - destination_db  
  
networks:
  etl_network:
    driver: bridge